//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XiangMuMing
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollegeDetail()
        {
            this.GradeDatas = new HashSet<GradeData>();
        }
    
        public int CD_Index { get; set; }
        public string CD_University { get; set; }
        public string CD_Course { get; set; }
        public string CD_Traffic { get; set; }
        public string CD_ImageURL { get; set; }
        public string CD_DormitoryConditions { get; set; }
    
        public virtual CollegeDetail CollegeDetails1 { get; set; }
        public virtual CollegeDetail CollegeDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeData> GradeDatas { get; set; }
    }
}
