//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XiangMuMing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Useless
    {
        public int Indx { get; set; }
        public int JiaGe { get; set; }
        public int YouHuiQuan { get; set; }
        public int YuFuDingJin { get; set; }
    }
}
